### ISSUE TITLE
Fontawesome Entegre

### ISSUE THREAD

**Issue by tolgagnydnn** [zafer06/kolej#9]
Fontawesome kütüphanesini entegre edemedim. Entegre  edebilir misin? Entegre işlemi tamamlandığında okul listesinde yıldız iconları görmemiz gerekiyor.

**Comment by zafer06** [comment]
Fontawesome entegrasyonu tamamlandı. https://github.com/zafer06/kolej/commit/b5877973639e814572e1dbeb09b67e83d82545ec
